package com.remind.mapper;

import com.remind.domain.CoinXpath;
import com.remind.domain.CoinXpathExample;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CoinXpathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    int insert(CoinXpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    int insertSelective(CoinXpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    List<CoinXpath> selectByExample(CoinXpathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    CoinXpath selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoinXpath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoinXpath record);
}