package com.remind.persistence.domain;

import com.remind.persistence.BaseDomain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table coin_xpath
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CoinXpath extends BaseDomain {

    private Integer coinId;

    private String name;

    private String css;

    private String fluctuation;

    private String xpath;

    private Integer state;

    private Date gmtCreate;

    private Date gmtUpdate;

    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.coin_id
     *
     * @return the value of coin_xpath.coin_id
     *
     * @mbg.generated
     */
    public Integer getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.coin_id
     *
     * @param coinId the value for coin_xpath.coin_id
     *
     * @mbg.generated
     */
    public void setCoinId(Integer coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.name
     *
     * @return the value of coin_xpath.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.name
     *
     * @param name the value for coin_xpath.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.css
     *
     * @return the value of coin_xpath.css
     *
     * @mbg.generated
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.css
     *
     * @param css the value for coin_xpath.css
     *
     * @mbg.generated
     */
    public void setCss(String css) {
        this.css = css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.fluctuation
     *
     * @return the value of coin_xpath.fluctuation
     *
     * @mbg.generated
     */
    public String getFluctuation() {
        return fluctuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.fluctuation
     *
     * @param fluctuation the value for coin_xpath.fluctuation
     *
     * @mbg.generated
     */
    public void setFluctuation(String fluctuation) {
        this.fluctuation = fluctuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.xpath
     *
     * @return the value of coin_xpath.xpath
     *
     * @mbg.generated
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.xpath
     *
     * @param xpath the value for coin_xpath.xpath
     *
     * @mbg.generated
     */
    public void setXpath(String xpath) {
        this.xpath = xpath;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.state
     *
     * @return the value of coin_xpath.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.state
     *
     * @param state the value for coin_xpath.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.gmt_create
     *
     * @return the value of coin_xpath.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.gmt_create
     *
     * @param gmtCreate the value for coin_xpath.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.gmt_update
     *
     * @return the value of coin_xpath.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.gmt_update
     *
     * @param gmtUpdate the value for coin_xpath.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}