package com.remind.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table coin_xpath
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CoinXpath implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.coin_id
     *
     * @mbg.generated
     */
    private Integer coinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.css
     *
     * @mbg.generated
     */
    private String css;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.fluctuation
     *
     * @mbg.generated
     */
    private String fluctuation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.xpath
     *
     * @mbg.generated
     */
    private String xpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_xpath.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coin_xpath
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.id
     *
     * @return the value of coin_xpath.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.id
     *
     * @param id the value for coin_xpath.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.coin_id
     *
     * @return the value of coin_xpath.coin_id
     *
     * @mbg.generated
     */
    public Integer getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.coin_id
     *
     * @param coinId the value for coin_xpath.coin_id
     *
     * @mbg.generated
     */
    public void setCoinId(Integer coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.name
     *
     * @return the value of coin_xpath.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.name
     *
     * @param name the value for coin_xpath.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.css
     *
     * @return the value of coin_xpath.css
     *
     * @mbg.generated
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.css
     *
     * @param css the value for coin_xpath.css
     *
     * @mbg.generated
     */
    public void setCss(String css) {
        this.css = css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.fluctuation
     *
     * @return the value of coin_xpath.fluctuation
     *
     * @mbg.generated
     */
    public String getFluctuation() {
        return fluctuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.fluctuation
     *
     * @param fluctuation the value for coin_xpath.fluctuation
     *
     * @mbg.generated
     */
    public void setFluctuation(String fluctuation) {
        this.fluctuation = fluctuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.xpath
     *
     * @return the value of coin_xpath.xpath
     *
     * @mbg.generated
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.xpath
     *
     * @param xpath the value for coin_xpath.xpath
     *
     * @mbg.generated
     */
    public void setXpath(String xpath) {
        this.xpath = xpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.is_delete
     *
     * @return the value of coin_xpath.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.is_delete
     *
     * @param isDelete the value for coin_xpath.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.state
     *
     * @return the value of coin_xpath.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.state
     *
     * @param state the value for coin_xpath.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.gmt_create
     *
     * @return the value of coin_xpath.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.gmt_create
     *
     * @param gmtCreate the value for coin_xpath.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_xpath.gmt_update
     *
     * @return the value of coin_xpath.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_xpath.gmt_update
     *
     * @param gmtUpdate the value for coin_xpath.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}