server:
  port: 8081
spring:
  redis:
    cache:
      host: 106.14.164.102:6379
      password: 123456
      maxIdle:
      minIdle:
      maxTotal:
      maxWaitMillis: 5000
  datasource:
    url: jdbc:mysql://106.14.164.102:3306/remind
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
